# Luke Lai
# 1355154
# luelai
# 11/11/14
# Makefile
# Makefile for list.c
CC = gcc
CFLAGS = -std=c99 -Wall -Werror -Wfatal-errors -g
OUTPUT = list

test: ${OUTPUT}
	./${OUTPUT}

clean:
	rm -f *.o

spotless: clean
	rm -f ${OUTPUT}

.PHONY: clean spotless test
